### ISSUE TITLE
Computing land permissions incorrectly

### ISSUE THREAD

**Issue by EibrielInv** [decentraland/linker-dapp#14]
When trying to deploy Golfcraft the DApp says the address `0xCF10CD8B5Dc2323B1eb6de6164647756BAd4dE4d` don't have permissions over some of the lands, but it does.

The account `0x598f8af1565003AE7456DaC280a18ee826Df7a2c` can deploy without issues. The owner of the lands is a third account.

Interestingly the address `0xCF10CD8B5Dc2323B1eb6de6164647756BAd4dE4d` can deploy without problems when setting the target to testing ( `dcl deploy --skip-build --target peer-testing.decentraland.org` ).

Info that may be useful: the scene covers 1 state ([link](https://opensea.io/assets/ethereum/0x959e104e1a4db6317fa58f8295f586e1a978c297/3709)) and 3 individual lands ([link](https://opensea.io/assets/ethereum/0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d/16333553612205046246241981156724874149842), [link](https://opensea.io/assets/ethereum/0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d/16673835979125984709705355764156642361298), [link](https://opensea.io/assets/ethereum/0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d/17014118346046923173168730371588410572754)).

Lands as set in the `scene.json` file:
```
[
      "47,-46","48,-46","49,-46",
      "47,-45","48,-45","49,-45",
      "47,-44","48,-44","49,-44",
      "47,-43","48,-43","49,-43"
    ]
```

Screenshot showing the issue:

![imagen](https://user-images.githubusercontent.com/172656/201435209-9b4b1d26-33ff-482b-8fe0-bdb59814bcb3.png)

![imagen](https://user-images.githubusercontent.com/172656/201435249-53ed765a-4f12-4cc7-a507-c4f3ace0fc6f.png)

![imagen](https://user-images.githubusercontent.com/172656/201435277-f2bea5db-3f8f-4d79-9ac9-5134ac840ae3.png)

![imagen](https://user-images.githubusercontent.com/172656/201435341-ae704d91-61c3-4ce8-a76e-b9fc494b7a71.png)

**Comment by menduz** [comment]
ack

**Comment by EibrielInv** [comment]
Closing since apparently the address `0xCF10CD8B5Dc2323B1eb6de6164647756BAd4dE4d` didn't have permission over the individual lands.
